name: antiphishing
description: "Trabalho de Conclusão de Curso (TCC)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  vector_graphics: ^1.1.9+1
  copy_with_extension: ^5.0.4
  flutter_bloc: ^8.1.6
  copy_with_extension_gen: ^5.0.4
  get_it: ^7.7.0
  injectable: ^2.4.2
  http: ^1.2.2
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

dev_dependencies:
  build_runner: ^2.0.0
  injectable_generator: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  vector_graphics_compiler: ^1.1.9+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
