name: antiphishing
description: "Trabalho de Conclusão de Curso (TCC)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  vector_graphics: ^1.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  vector_graphics_compiler: ^1.1.9+1

flutter:
  uses-material-design: true
  assets:
    - assets/images
